// REGISTER USER
POST http://localhost:5000/users/register
Content-Type: application/json  

{
  "email":"ahmad@gmail.com",
  "first_name":"Muhammad",
  "last_name":"Fadilah",
  "password": "12345678",
  "confirm_password": "12345678"
}

###
// LOGIN
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "email":"ahmad@gmail.com",
  "password": "12345678",
  "confirm_password": "12345678"
}

// GET ALL USER
###
GET http://localhost:5000/users/view

//UPDATE USER
###
PUT http://localhost:5000/users/view/1

{
  "first_name": "Joko",
  "last_name": "Santoso"
}
###
// UPDATE GAMBAR
POST http://localhost:5000/users/images/1
form-data
profileImage  file
###
// GET ALL BANNER
GET http://localhost:5000/information/banner
###
// GET ALL SERVICE
GET http://localhost:5000/information/service
###
// POST TRANSACTION
http://localhost:5000/transaction/transaction
Content-Type: application/json 

{
  "invoice_number": "INV17082023-001",
  "service_code": "PLN"
}
###
// TOP UP TRANSACTION
POST http://localhost:5000/transaction/topup
###
// GET BALANCE TRANSACTION
GET http://localhost:5000//transaction/amount
###
// GET HISTORY TRANSACTION
GET http://localhost:5000/transaction/history


LINK RAILWAY :
https://pulsabe-production.up.railway.app/users/register